// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gateway-service/internal/conf"
	"gateway-service/internal/server"
	"gateway-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	timeService := service.NewTimeService()
	httpServer := server.NewHTTPServer(confServer, timeService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
