// Code generated by Kitex v0.1.4. DO NOT EDIT.
package timeservice

import (
	"github.com/cloudwego/kitex/server"
	"kitex-demo/time-service/kitex_gen/pbgo/timepb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler timepb.TimeService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
