// Code generated by goctl. DO NOT EDIT!
// Source: time.proto

package server

import (
	"context"

	"gozero-demo/pb/pbgo/timepb"
	"gozero-demo/time-service/internal/logic"
	"gozero-demo/time-service/internal/svc"
)

type TimeServiceServer struct {
	svcCtx *svc.ServiceContext
	timepb.UnimplementedTimeServiceServer
}

func NewTimeServiceServer(svcCtx *svc.ServiceContext) *TimeServiceServer {
	return &TimeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TimeServiceServer) GetTime(ctx context.Context, in *timepb.GetTimeReq) (*timepb.GetTimeResp, error) {
	l := logic.NewGetTimeLogic(ctx, s.svcCtx)
	return l.GetTime(in)
}
