apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reset-counter
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reset-counter
              image: registry:5000/reset-counter
              args:
              - reset-counter
          restartPolicy: OnFailure