// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"time-service/internal/conf"
	"time-service/internal/server"
	"time-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	greeterService := service.NewTimeService()
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	app := newApp(logger,  grpcServer)
	return app, func() {
	}, nil
}
