// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.5

package gateway

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type GatewayHTTPServer interface {
	GetTime(context.Context, *GetTimeRequest) (*GetTimeReply, error)
}

func RegisterGatewayHTTPServer(s *http.Server, srv GatewayHTTPServer) {
	r := s.Route("/")
	r.GET("/time/getTime", _Gateway_GetTime0_HTTP_Handler(srv))
}

func _Gateway_GetTime0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTimeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.gateway.Gateway/GetTime")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTime(ctx, req.(*GetTimeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTimeReply)
		return ctx.Result(200, reply)
	}
}

type GatewayHTTPClient interface {
	GetTime(ctx context.Context, req *GetTimeRequest, opts ...http.CallOption) (rsp *GetTimeReply, err error)
}

type GatewayHTTPClientImpl struct {
	cc *http.Client
}

func NewGatewayHTTPClient(client *http.Client) GatewayHTTPClient {
	return &GatewayHTTPClientImpl{client}
}

func (c *GatewayHTTPClientImpl) GetTime(ctx context.Context, in *GetTimeRequest, opts ...http.CallOption) (*GetTimeReply, error) {
	var out GetTimeReply
	pattern := "/time/getTime"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.gateway.Gateway/GetTime"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
